param(
    [string]$FolderPath
)

$Desktop = [Environment]::GetFolderPath("Desktop")
$TimeStamp = Get-Date -Format "yyyyMMdd_HHmmss"

$HtmlFile = Join-Path $Desktop "FolderReport_$TimeStamp.html"
$PdfFile  = Join-Path $Desktop "FolderReport_$TimeStamp.pdf"

$Files = Get-ChildItem -LiteralPath $FolderPath -File

$TotalSizeMB = [math]::Round(
    (($Files | Measure-Object Length -Sum).Sum / 1MB),2
)

$html = @"
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Folder Report</title>

<style>

body{
    font-family: Segoe UI, Arial, sans-serif;
    margin:40px;
}

h1{
    text-align:center;
}

.summary{
    background:#f5f5f5;
    padding:15px;
    border-radius:8px;
    margin-bottom:20px;
}

table{
    width:100%;
    border-collapse:collapse;
}

th{
    background:#d9e8ff;
    border:1px solid #999;
    padding:8px;
}

td{
    border:1px solid #999;
    padding:6px;
}

tr:nth-child(even){
    background:#f8f8f8;
}

.footer{
    margin-top:20px;
    font-size:10pt;
}

</style>

</head>
<body>

<h1>Folder Information Report</h1>

<div class="summary">
<b>Folder:</b> $FolderPath<br>
<b>Total Files:</b> $($Files.Count)<br>
<b>Total Size:</b> $TotalSizeMB MB<br>
<b>Generated:</b> $(Get-Date)
</div>

<table>

<tr>
<th>S.No.</th>
<th>File Name</th>
<th>Extension</th>
<th>Size (KB)</th>
<th>Created</th>
<th>Modified</th>
</tr>

"@

$i = 1

foreach($file in $Files)
{
    $sizeKB = [math]::Round($file.Length/1KB,2)

    $html += @"
<tr>
<td>$i</td>
<td>$($file.Name)</td>
<td>$($file.Extension)</td>
<td>$sizeKB</td>
<td>$($file.CreationTime)</td>
<td>$($file.LastWriteTime)</td>
</tr>
"@

    $i++
}

$html += @"

</table>

<div class="footer">
Generated by Sudarshan Tools
</div>

</body>
</html>
"@

$html | Set-Content $HtmlFile -Encoding UTF8

$Edge = "$env:ProgramFiles (x86)\Microsoft\Edge\Application\msedge.exe"

if(-not (Test-Path $Edge))
{
    $Edge = "$env:ProgramFiles\Microsoft\Edge\Application\msedge.exe"
}

Start-Process `
    $Edge `
    "--headless --disable-gpu --print-to-pdf=`"$PdfFile`" `"$HtmlFile`"" `
    -Wait

Start-Process $PdfFile